-- MySQL Script generated by MySQL Workbench
-- Sat Jun  9 18:24:43 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Addresses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Addresses` (
  `addressId` INT(11) NOT NULL AUTO_INCREMENT,
  `addressLine1` VARCHAR(45) NULL DEFAULT NULL,
  `addressLine2` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `state` VARCHAR(45) NULL DEFAULT NULL,
  `postalCode` VARCHAR(6) NULL DEFAULT NULL,
  PRIMARY KEY (`addressId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`userType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`userType` ;

CREATE TABLE IF NOT EXISTS `mydb`.`userType` (
  `userTypeId` INT NOT NULL AUTO_INCREMENT,
  `userTypeName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userTypeId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `userId` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NULL DEFAULT NULL,
  `lastName` VARCHAR(45) NULL DEFAULT NULL,
  `phoneNumber` VARCHAR(10) NULL DEFAULT NULL,
  `notificationState` TINYINT(4) NOT NULL,
  `userTypeId` INT NOT NULL,
  PRIMARY KEY (`userId`),
  INDEX `fk_Users_userType1_idx` (`userTypeId` ASC),
  CONSTRAINT `fk_Users_userType1`
    FOREIGN KEY (`userTypeId`)
    REFERENCES `mydb`.`userType` (`userTypeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Children`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Children` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Children` (
  `childId` INT(11) NOT NULL AUTO_INCREMENT,
  `userId` INT(11) NOT NULL,
  `firstName` VARCHAR(45) NULL DEFAULT NULL,
  `lastName` VARCHAR(45) NULL DEFAULT NULL,
  `childDob` DATE NULL DEFAULT NULL,
  `childAllergies` VARCHAR(45) NULL DEFAULT NULL,
  `emergencyContactNum` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`childId`),
  INDEX `fk_Children_Users1_idx` (`userId` ASC),
  CONSTRAINT `fk_Children_Users1`
    FOREIGN KEY (`userId`)
    REFERENCES `mydb`.`Users` (`userId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Organizations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Organizations` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Organizations` (
  `organizationId` INT(11) NOT NULL AUTO_INCREMENT,
  `addressId` INT(11) NOT NULL,
  `organizationName` VARCHAR(45) NULL DEFAULT NULL,
  `organizationDescription` TEXT NULL DEFAULT NULL,
  `phoneNumber` INT(11) NULL DEFAULT NULL,
  `organizationWebsite` VARCHAR(45) NULL DEFAULT NULL,
  `userId` INT(11) NOT NULL,
  PRIMARY KEY (`organizationId`),
  INDEX `fk_Organizations_Addresses1_idx` (`addressId` ASC),
  INDEX `fk_Organizations_userId_id` (`userId` ASC),
  CONSTRAINT `fk_Communities_Addresses1`
    FOREIGN KEY (`addressId`)
    REFERENCES `mydb`.`Addresses` (`addressId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Organizations_userId_id`
    FOREIGN KEY (`userId`)
    REFERENCES `mydb`.`Users` (`userId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`Events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Events` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Events` (
  `eventId` INT(11) NOT NULL AUTO_INCREMENT,
  `organizationId` INT(11) NULL DEFAULT NULL,
  `eventName` VARCHAR(45) NULL DEFAULT NULL,
  `eventDescription` TEXT NULL DEFAULT NULL,
  `eventPrice` INT NULL DEFAULT NULL,
  `minAge` INT NULL DEFAULT NULL,
  `maxAge` INT NULL DEFAULT NULL,
  `eventDate` DATETIME NULL DEFAULT NULL,
  `registrationOpen` DATETIME NULL DEFAULT NULL,
  `registrationClose` DATETIME NULL DEFAULT NULL,
  `enddate` DATETIME NULL DEFAULT NULL,
  `eventType` SET('Day Camp', 'Summer Camp', 'Overnight Camp', 'Half Day', 'Full Day', 'One Week', 'Two Week', 'Full Summer', 'Other') NULL DEFAULT NULL,
  `eventCategory` SET('Academics', 'Animals & Farms', 'Arts & Crafts', 'Language & Culture', 'Multi-Activity Day Camp', 'Nature & Environment', 'Overnight Camp', 'Performing Arts', 'Religious Programs', 'Science & Technology', 'Special Needs', 'Sports & Fitness') NULL DEFAULT NULL,
  PRIMARY KEY (`eventId`),
  INDEX `fk_Events_Organizations1_idx` (`organizationId` ASC),
  CONSTRAINT `fk_Events_Communities1`
    FOREIGN KEY (`organizationId`)
    REFERENCES `mydb`.`Organizations` (`organizationId`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`ChildEvents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ChildEvents` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ChildEvents` (
  `childId` INT(11) NULL,
  `eventId` INT(11) NOT NULL,
  `userId` INT(11) NOT NULL,
  PRIMARY KEY (`eventId`, `userId`),
  INDEX `fk_Children_has_Events_Events1_idx` (`eventId` ASC),
  INDEX `fk_Children_has_Events_Children1_idx` (`childId` ASC),
  INDEX `fk_ChildEvents_Users1_idx` (`userId` ASC),
  CONSTRAINT `fk_Children_has_Events_Children1`
    FOREIGN KEY (`childId`)
    REFERENCES `mydb`.`Children` (`childId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Children_has_Events_Events1`
    FOREIGN KEY (`eventId`)
    REFERENCES `mydb`.`Events` (`eventId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ChildEvents_Users1`
    FOREIGN KEY (`userId`)
    REFERENCES `mydb`.`Users` (`userId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`EventAddresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EventAddresses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EventAddresses` (
  `eventId` INT(11) NOT NULL,
  `addressId` INT(11) NOT NULL,
  PRIMARY KEY (`eventId`, `addressId`),
  INDEX `fk_Events_has_Addresses_Addresses1_idx` (`addressId` ASC),
  INDEX `fk_Events_has_Addresses_Events1_idx` (`eventId` ASC),
  CONSTRAINT `fk_Events_has_Addresses_Addresses1`
    FOREIGN KEY (`addressId`)
    REFERENCES `mydb`.`Addresses` (`addressId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Events_has_Addresses_Events1`
    FOREIGN KEY (`eventId`)
    REFERENCES `mydb`.`Events` (`eventId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`userAddresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`userAddresses` ;

CREATE TABLE IF NOT EXISTS `mydb`.`userAddresses` (
  `userId` INT(11) NOT NULL,
  `addressId` INT(11) NOT NULL,
  PRIMARY KEY (`userId`, `addressId`),
  INDEX `fk_Users_has_Addresses_Addresses1_idx` (`addressId` ASC),
  INDEX `fk_Users_has_Addresses_Users1_idx` (`userId` ASC),
  CONSTRAINT `fk_Users_has_Addresses_Users1`
    FOREIGN KEY (`userId`)
    REFERENCES `mydb`.`Users` (`userId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Addresses_Addresses1`
    FOREIGN KEY (`addressId`)
    REFERENCES `mydb`.`Addresses` (`addressId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
